/* Classic BNF (Backus-Naur Form) Example */
/* This is the original notation from the 1960s */

<program> ::= <statement> | <program> ";" <statement>

<statement> ::= <assignment> | <expression>

<assignment> ::= <identifier> "=" <expression>

<expression> ::= <term> 
               | <expression> "+" <term> 
               | <expression> "-" <term>

<term> ::= <factor> 
         | <term> "*" <factor> 
         | <term> "/" <factor>

<factor> ::= <number> 
           | <identifier> 
           | "(" <expression> ")"
           | "-" <factor>

<number> ::= <digit> | <number> <digit>

<identifier> ::= <letter> | <identifier> <letter> | <identifier> <digit>

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
           | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
           | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
           | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

/* BNF Notation Reference:
   ::=          "is defined as"
   |            "or" (alternative)
   < >          non-terminal symbol
   " "          terminal symbol (literal)
   /* */        comment (some variants use (* *))
   
   Note: BNF is more verbose than EBNF because it doesn't have
   repetition operators { } and optional operators [ ]
*/